spring:
  # 1. Database (MySQL) 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/livechat_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234


  # 2. JPA (Hibernate) 설정
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # 3. Web & Server 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 4. Logging 설정
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

server:
  port: 8080