name: CD - Deploy to EC2

on:
  workflow_run:
    workflows: [ "CI - Build and Push to Docker Hub" ]
    types:
      - completed
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/livechat
  IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Transfer docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/"

      - name: Deploy to Public EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cat > .env << EOF
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            IMAGE_TAG=${{ env.IMAGE_TAG }}
            SERVER_PORT=${{ secrets.SERVER_PORT }}
            DB_URL=${{ secrets.DB_URL }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            EOF
            
            docker-compose down
            
            docker-compose pull spring-app
            
            docker-compose up -d spring-app
            
            docker ps | grep spring-app
            
            docker image prune -af
